<!--
 * @Author: 黄遥
 * @Date: 2020-03-26 17:23:47
 * @LastEditors: 黄遥
 * @LastEditTime: 2020-03-27 15:03:19
 * @Description: file content
 -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    new Promise(function(resolve,reject){
      resolve(3)
    }).then(function(val){
      console.log(val)
    })
    console.log(1)
    setTimeout(() => {
      console.log(2)
    }, 0);

    //Promise对象实现Ajax
    const getJSON = function(url){
      const promise = new Promise(function(resolve,reject){
        const handler = function() {
          if(this.readyState !== 4){
            return;
          }
          if(this.status === 200) {
            resolve(this.response)
          }else {
            reject(new Error(this.statusText))
          }
        }
        const client = new XMLHttpRequest();
        client.open("GET", url);
        client.onreadystatechange = handler;
        client.responseType = "json";
        client.setRequestHeader("Accept","application/json");
        client.send();
      })
      return promise
    }
    // getJSON("/posts.json").then(function(json){
    //   console.log(json)
    // },function(error){
    //   console.error('出错了',error)
    // }).catch(function(err){
    //   console.log(err)
    // })

    //resolve 和 reject 都是可以带参数的，参数会传递给回调函数，reject函数的参数通常是Error，resolve函数的参数除了正常值外，还可能是个promise
    const p1 = new Promise(function(resolve,reject){
      console.log(new Date().getSeconds())
      setTimeout(() => {
        reject(new Error('fail'))
      }, 3000);
    })
    const p2 = new Promise(function(resolve,reject){
      console.log(new Date().getSeconds())
      setTimeout(() => {
        resolve(p1)
      }, 1000);
    })
    p2.then(function(res){
      console.log(new Date().getSeconds())
      console.log(res)
    }).catch(function(error){
      console.log(new Date().getSeconds())
      console.log(error)
    })
    /**
    上面代码中，p1和p2都是 Promise 的实例，但是p2的resolve方法将p1作为参数，即一个异步操作的结果是返回另一个异步操作。
注意，这时p1的状态就会传递给p2，也就是说，p1的状态决定了p2的状态。如果p1的状态是pending，那么p2的回调函数就会等待p1的状态改变；如果p1的状态已经是resolved或者rejected，那么p2的回调函数将会立刻执行。
    */

    //注意调用resolve或reject并不会终结Promise的参数函数的执行
    new Promise(function(resolve,reject){
      resolve(1);
      console.log(2);
    }).then(function(r){
      console.log(r)
    });
    // 2
    // 1

    //一般总是建议，Promise 对象后面要跟catch方法，这样可以处理 Promise 内部发生的错误
    //catch 方法返回的还是一个 Promise 对象，因此后面还可以接着调用then方法
    const someAsyncThing = function() {
      return new Promise(function(resolve,reject){
        resolve(x+2)
      })
    }
    someAsyncThing().catch(function(error){
      console.log('oh no', error)
      return error
    }).then(function(res){
      console.log(res)
      console.log('carry on')
    })

    // finally 不管前面的Promise是 fulfilled 还是 rejected，都会执行回调函数
    // finally 本质上是 then 方法的特例
    Promise
    .finally(() => {
      // 语句
    })
    // 等同于
    Promise
    .then(
      result => {
        // 语句
        return result;
      },
      error => {
        // 语句
        throw error;
      }
    )


    // finally 方法总是会返回原来的值
    Promise.resolve(3).finally(() => {}).then(res => {
      console.log(res)
    })

    //promise.all 接收一个数组作为参数，数组中都是 Promise 实例，如果不是，就要先调用 Promise.resolve 方法，
    //将参数转为 Promise 实例
    const promises = [2,3,5,7,11,13].map(function(id){
      return getJSON('/post/' + id + '.json')
    })
    Promise.all(promises).then(function(posts){
      // ....
    }).catch(function(reason){
      // ....
    })
    /*注意：如果作为参数的 Promise 实例，自己定义了catch方法，那么它一旦被rejected，并不会触发Promise.all()的catch方法*/


    /*
    Promise.allSettled()方法接受一组 Promise 实例作为参数，包装成一个新的 Promise 实例。
    只有等到所有这些参数实例都返回结果，不管是fulfilled还是rejected，包装实例才会结束。该方法由 ES2020 引入
    */
    //有时候，我们不关心异步操作的结果，只关心这些操作有没有结束，这时，Promise.allSettled()方法就很有用
    const promises = [ fetch('index.html'), fetch('https://does-not-exist/') ];
    const results = await Promise.allSettled(promises);

    // 过滤出成功的请求
    const successfulPromises = results.filter(p => p.status === 'fulfilled');

    // 过滤出失败的请求，并输出原因
    const errors = results
      .filter(p => p.status === 'rejected')
      .map(p => p.reason);


    //我们可以将图片的加载写成一个Promise，一旦加载完成，Promise的状态就发生变化
    const preloadImage = function(path){
      return new Promise(function(resolve,reject){
        const image = new Image();
        image.onload = resolve;
        image.onerror = reject;
        image.src = path;
      })
    }
  </script>
</body>
</html>